
const LandingPageBody = ({onSignUpClick}) => {
  return (
    <main className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8 text-white">
      <div className="px-4 py-6 sm:px-0 text-center">
        <h1 className="text-4xl font-bold">Navigate Your Career Journey with Confidence</h1>
        <p className="mt-4 text-xl text-gray-400">Track applications, generate tailored cover letters, and land your dream job with AIpplicant</p>
        <button onClick={onSignUpClick} className="mt-6 bg-indigo-600 text-white px-6 py-3 rounded-md hover:bg-indigo-700 transition duration-300">
          Get Started for Free
        </button>
      </div>

      <div className="mt-12 grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="bg-gray-800 p-6 rounded-lg border border-gray-700">
          <h2 className="text-2xl font-bold mb-4">AI-Powered Cover Letters</h2>
          <p className="text-gray-400 mb-4">Stand out from the crowd with personalized cover letters generated by our advanced AI. Tailored to each job and highlighting your unique skills.</p>
          <div className="flex justify-center">
            <img 
              src="https://res.cloudinary.com/dr9aiqtjj/image/upload/v1724854054/AI_coverletter2_elditw.png" 
              alt="AI-Powered Cover Letters" 
              className="w-auto h-80 rounded-lg border border-gray-600 object-cover"
            />
          </div>
        </div>

        <div className="bg-gray-800 p-6 rounded-lg border border-gray-700">
          <h2 className="text-2xl font-bold mb-4">Effortless Application Tracking</h2>
          <p className="text-gray-400 mb-4">Stay organized and never miss a deadline. Keep all your job applications in one place, from initial submission to final offer.</p>
          <img 
            src="https://res.cloudinary.com/dr9aiqtjj/image/upload/v1724852194/Aipplicant_body_hj1hyf.png" 
            alt="Application Tracking Interface" 
            className="w-full h-auto rounded-lg border border-gray-600"
          />
        </div>
      </div>

      <div className="mt-12 text-center">
        <h2 className="text-2xl font-bold mb-4">Ready to take control of your job search?</h2>
        <button onClick={onSignUpClick} className="bg-indigo-600 text-white px-8 py-3 rounded-md hover:bg-indigo-700 transition duration-300 text-lg">
          Sign up now for free!
        </button>
      </div>
    </main>
  );
};

export default LandingPageBody